/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Acciones.VentaControlador;
import Acciones.Exportar;
import Modelo.Producto;
import Extras.DatoProducto;
import Extras.Ticket;
import Modelo.Cliente;
import Modelo.VentaTabla;
import javax.swing.*;
import java.awt.Image;
import java.net.URI;
import java.net.URL;
import javax.swing.text.html.HTML;
import java.util.ArrayList;
/**
 *
 * @author marti
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    private VentaControlador ventaControlador = new VentaControlador();
    private ArrayList<Producto> productosActuales = new ArrayList<>();
    public Formulario() {
        initComponents();

        // conectar la tabla
        tblCarrito.setModel(ventaControlador.getVentaTabla());
        for (String cate : DatoProducto.getCategorias()) {
            cmbCategoria.addItem(cate);
        }
        cargarProductos();
    }
    
    private void cargarProductos(){
    cmbProducto.removeAllItems();
    
    String categoria = (String)cmbCategoria.getSelectedItem();
    productosActuales = DatoProducto.getProductos(categoria);
    for (Producto p : productosActuales){
            cmbProducto.addItem(p);
    }
        mostrarImagen();
    }
    
    private void mostrarImagen() {
    Producto p = (Producto) cmbProducto.getSelectedItem();
    if (p == null) return;
        try {
            URL url = new URL(p.getImagen());
            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);
            lblImagen.setIcon(new ImageIcon(img));
           
        } catch (Exception e) {
            lblImagen.setText("Sin imagen");
        }
    
        lblstock.setText(">>" + p.getStock());
    }     
    
    private void actualizarTotales(){
    lblSubtotal.setText(" " + ventaControlador.getSubtotal());
    lblIVA.setText(" " + ventaControlador.getIVA());
    lblTotal.setText(" " + ventaControlador.getTotal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Datosclienepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        nombresdefieldspanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelproductos = new javax.swing.JPanel();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbProducto = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        spnCantidad = new javax.swing.JSpinner();
        chkVendido = new javax.swing.JCheckBox();
        btnAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblstock = new javax.swing.JLabel();
        pancelcarrito = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        paneltotalybotones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        sub = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        iv = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnNueva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        Datosclienepanel.setBackground(new java.awt.Color(153, 204, 255));
        Datosclienepanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Datos del cliente");
        Datosclienepanel.add(jLabel1);

        txtNombre.setPreferredSize(new java.awt.Dimension(70, 22));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        Datosclienepanel.add(txtNombre);

        txtApellidos.setPreferredSize(new java.awt.Dimension(70, 22));
        Datosclienepanel.add(txtApellidos);

        txtEdad.setPreferredSize(new java.awt.Dimension(70, 22));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        Datosclienepanel.add(txtEdad);

        nombresdefieldspanel.setBackground(new java.awt.Color(153, 204, 255));
        nombresdefieldspanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setText("             ");
        nombresdefieldspanel.add(jLabel5);

        jLabel2.setText("          Nombre");
        nombresdefieldspanel.add(jLabel2);

        jLabel3.setText("      Apellidos");
        nombresdefieldspanel.add(jLabel3);

        jLabel4.setText("       Edad");
        nombresdefieldspanel.add(jLabel4);

        panelproductos.setBackground(new java.awt.Color(204, 204, 255));
        panelproductos.setForeground(new java.awt.Color(255, 255, 255));
        panelproductos.setLayout(new javax.swing.BoxLayout(panelproductos, javax.swing.BoxLayout.Y_AXIS));

        cmbCategoria.setBackground(new java.awt.Color(255, 204, 255));
        cmbCategoria.setMaximumSize(new java.awt.Dimension(200, 50));
        cmbCategoria.setName(""); // NOI18N
        cmbCategoria.setPreferredSize(new java.awt.Dimension(72, 30));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        panelproductos.add(cmbCategoria);

        cmbProducto.setBackground(new java.awt.Color(255, 204, 255));
        cmbProducto.setMaximumRowCount(20);
        cmbProducto.setMaximumSize(new java.awt.Dimension(200, 50));
        cmbProducto.setPreferredSize(new java.awt.Dimension(72, 30));
        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });
        panelproductos.add(cmbProducto);

        jPanel7.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(162, 50));

        lblImagen.setText("           ");
        lblImagen.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel7.add(lblImagen);

        panelproductos.add(jPanel7);

        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(162, 30));
        jPanel6.add(spnCantidad);

        chkVendido.setText("Vendido");
        chkVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVendidoActionPerformed(evt);
            }
        });
        jPanel6.add(chkVendido);

        panelproductos.add(jPanel6);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelproductos.add(btnAgregar);

        jLabel6.setText("Stock:");
        panelproductos.add(jLabel6);

        lblstock.setText("    ");
        panelproductos.add(lblstock);

        pancelcarrito.setBackground(new java.awt.Color(255, 204, 255));

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pancelcarrito.setViewportView(tblCarrito);

        paneltotalybotones.setBackground(new java.awt.Color(255, 153, 153));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        paneltotalybotones.setLayout(flowLayout1);

        jPanel1.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        sub.setText("SUBTOTAL: ");
        jPanel1.add(sub);

        lblSubtotal.setText("0.00");
        jPanel1.add(lblSubtotal);

        iv.setText("IVA (16%:)");
        jPanel1.add(iv);

        lblIVA.setText("0.00");
        jPanel1.add(lblIVA);

        tot.setText("TOTAL: ");
        jPanel1.add(tot);

        lblTotal.setText("0.00");
        jPanel1.add(lblTotal);

        paneltotalybotones.add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar);

        btnTicket.setText("TICKET");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        jPanel2.add(btnTicket);

        btnExportar.setText("EXPORTAR");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        jPanel2.add(btnExportar);

        btnNueva.setText("NUEVA");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });
        jPanel2.add(btnNueva);

        paneltotalybotones.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Datosclienepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pancelcarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(paneltotalybotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(panelproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombresdefieldspanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Datosclienepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombresdefieldspanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pancelcarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paneltotalybotones, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void chkVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVendidoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Producto p = (Producto) cmbProducto.getSelectedItem();
        int cantidad = (int) spnCantidad.getValue();
        if (cantidad > p.getStock()){
            JOptionPane.showMessageDialog(this, "No hay suficientes productos para vender, solo tienes en stock" + p.getStock() + " unidades");
            return;
        }
        if (p == null) return;
        ventaControlador.agregarProducto(p, cantidad);
        chkVendido.setSelected(p.getStock() == 0);
        lblstock.setText(">>" + p.getStock());
        actualizarTotales();
        mostrarImagen();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        cargarProductos();
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        
        Cliente cliente = new Cliente(txtNombre.getText(), txtApellidos.getText(), 
                txtEdad.getText().isBlank() ? 0 : Integer.parseInt(txtEdad.getText()));
        String ticket = Ticket.construirTicket(ventaControlador.getVenta());
        JTextArea area = new JTextArea(ticket);
        area.setEditable(false);
        area.setFont(new java.awt.Font("Monospaced", 0, 12));
        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new java.awt.Dimension(400,300));
        JOptionPane.showMessageDialog(this, scroll, "Vista previa del ticket de la venta;:", JOptionPane.PLAIN_MESSAGE);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        JFileChooser fc = new JFileChooser();
        
        fc.setSelectedFile(new java.io.File("Ticket.txt"));
        
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            boolean chi = Exportar.exportarTicketTxt(ventaControlador.getVenta(), fc.getSelectedFile().getAbsolutePath());
            JOptionPane.showMessageDialog(this, chi ? "archivo cuardado bn" : "Error al guardarlo");
            
            
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnExportarActionPerformed

    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
        mostrarImagen();        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblCarrito.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto de la tabla; ");
            return;
        }
        ventaControlador.eliminarProducto(fila);
        actualizarTotales();;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        ventaControlador.nuevaVenta();
        txtNombre.setText(" ");
        txtApellidos.setText(" ");
        txtEdad.setText(" ");
        chkVendido.setSelected(false);
        actualizarTotales();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Datosclienepanel;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnNueva;
    private javax.swing.JButton btnTicket;
    private javax.swing.JCheckBox chkVendido;
    private javax.swing.JComboBox<Object> cmbCategoria;
    private javax.swing.JComboBox<Object> cmbProducto;
    private javax.swing.JLabel iv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblstock;
    private javax.swing.JPanel nombresdefieldspanel;
    private javax.swing.JScrollPane pancelcarrito;
    private javax.swing.JPanel panelproductos;
    private javax.swing.JPanel paneltotalybotones;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JLabel sub;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JLabel tot;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
